
import { DM_Sans, Instrument_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";






const dmSansReg = DM_Sans({
  variable: 'dm-sans-regular',
  subsets:['latin'],
  weight:['400'],
  style:['normal', 'italic']
})
const dmSansBold = DM_Sans({
  variable:'dm-sans-bold',
  subsets:['latin'],
  weight:['700'],
  style:['normal', 'italic']
})
const instSans = Instrument_Sans({
  variable:'dm-sans-bold',
  subsets:['latin'],
  weight:['700'],
  style:['normal', 'italic']
})

export const metadata = {
  title: "Visionary Advance Web Design and Development",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`$ ${instSans.variable} ${dmSansReg.variable} ${dmSansBold.variable} antialiased`}
      >
        <Header />
        
        {children} 
     
        <Footer variant = "default" />
      </body>
    </html>
  );
}
